/*
-- Query: select * from employee
LIMIT 0, 1000

-- Date: 2012-04-20 12:14
*/
INSERT INTO `EMPLOYEE` (`ID`,`VERSION`,`DATE_OF_BIRTH`,`FIRST_NAME`,`GENDER`,`LAST_NAME`,`MIDDLE_NAME`,`USER_ACCOUNT_ID`,`ORGANIZATION_UNIT_ID`,`DESIGNATION`) VALUES (1,0,'2012-04-02 00:00:00','Sowjanya',1,'Kurukuri',NULL,NULL,17,'DIRECTOR');
INSERT INTO `EMPLOYEE` (`ID`,`VERSION`,`DATE_OF_BIRTH`,`FIRST_NAME`,`GENDER`,`LAST_NAME`,`MIDDLE_NAME`,`USER_ACCOUNT_ID`,`ORGANIZATION_UNIT_ID`,`DESIGNATION`) VALUES (2,0,'1984-06-19 00:00:00','Vamsi',0,'Kurukuri',NULL,NULL,17,'DIRECTOR');
