/*
-- Query: select * from ORGANIZATION_UNIT
LIMIT 0, 1000

-- Date: 2012-04-20 12:18
*/
INSERT INTO `ORGANIZATION_UNIT` (`ID`,`VERSION`,`NAME`,`ORGANIZATION_ID`) VALUES (1,0,'Jaggampeta Branch',1);
INSERT INTO `ORGANIZATION_UNIT` (`ID`,`VERSION`,`NAME`,`ORGANIZATION_ID`) VALUES (2,0,'Rajahmundry Branch',1);
