/*
-- Query: select * from ORGANIZATION_ACCESS
LIMIT 0, 1000

-- Date: 2012-04-20 12:17
*/
INSERT INTO `ORGANIZATION_ACCESS` (`ID`,`VERSION`,`ORGANIZATION_ACCESS_TYPE`,`REF_ID`,`USER_ACCOUNT_ID`) VALUES (1,1,'ORGANIZATION_UNIT',17,2);
