/*
-- Query: select * from class
LIMIT 0, 1000

-- Date: 2012-04-20 10:03
*/
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (1,0,'LKG','Lower Kindergarten',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (2,0,'UKG','Upper Kindergarten',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (3,2,'I','First',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (4,2,'II','Second',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (5,0,'III','Third',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (6,0,'IV','Fourth',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (7,0,'V','Fifth',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (8,0,'VI','Sixth',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (9,0,'VII','Seventh',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (10,0,'VIII','Eighth',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (11,0,'IX','Ninth',1);
INSERT INTO `CLASS` (`ID`,`VERSION`,`CODE`,`NAME`,`ORGANIZATION_UNIT_ID`) VALUES (12,0,'X','Tenth',1);
