/*
-- Query: select * from ADDRESS
LIMIT 0, 1000

-- Date: 2012-04-20 12:21
*/
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (17,0,'Gokavaram Rd','Jaggampeta',NULL,'','','',0,'AP','500033','IND',17,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (18,0,'Main Road','Rajahmundry',NULL,'918832402331','918832402331','918832402331',0,'AP','533287','IND',18,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (19,0,'4408 CALEDONIA CREEK LN','PLANO','vamsikurukuri@gmail.com','9044166192','9044166192',NULL,0,'TX','75024','USA',NULL,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (20,0,'4408 CALEDONIA CREEK LN','PLANO','vamsikurukuri@gmail.com','9044166192','9044166192',NULL,0,'TX','75024','USA',NULL,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (21,0,'4408 CALEDONIA CREEK LN','PLANO','vamsikurukuri@gmail.com','9044166192','9044166192',NULL,0,'TX','75024','USA',NULL,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (22,0,'4408 CALEDONIA CREEK LN','PLANO','vamsikurukuri@gmail.com','9044166192','9044166192',NULL,0,'TX','75024','USA',NULL,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (23,0,'4408 CALEDONIA CREEK LN','PLANO','vamsikurukuri@gmail.com','9044166192','9044166192',NULL,0,'TX','75024','USA',NULL,NULL,NULL);
INSERT INTO `ADDRESS` (`ID`,`VERSION`,`ADDRESS`,`CITY`,`EMAIL`,`HOME_PHONE_NR`,`MOBILE_NR`,`OFFICE_PHONE_NR`,`IS_PRIMARY`,`STATE`,`ZIPCODE`,`COUNTRY_ID`,`OGANIZATION_UNIT_ID`,`RELATION_ID`,`STUDENT_ID`) VALUES (24,0,'4408 CALEDONIA CREEK LN','PLANO','vamsikurukuri@gmail.com','9044166192','9044166192',NULL,0,'TX','75024','USA',NULL,NULL,NULL);
