
INSERT INTO USER_ACCOUNT VALUES (1,now(),'apeironsol',1,0,0,1,0,'/x/2nTS83P0nTK8Eio/mXB701NbgYbvw',NULL,'Apeiron123Sol');
INSERT INTO USER_ROLE VALUES (1,now(),'apeironsol',0,'ROLE_APEIRONSOL',1);

INSERT INTO COUNTRY (`ISO3_CODE`,`ISO2_CODE`,`NAME`,`NUM_CODE`) VALUES ('IND','IN','India',356);

commit;