/**
 * Alter columns
 */
drop table employee_salary;

drop table salary;

drop table BATCH_LOG;
drop table BATCH_LOG_MESSAGE;
drop table BRANCH_RULE;


ALTER TABLE STUDENT DROP FOREIGN KEY UQ_EXT_ADMIS_NR_BRANCH_ID;

ALTER TABLE SEQUENCE_GENERATOR DROP COLUMN BRANCH_ID;

/**
 * Added by Sunny for Admission Process Changes
 */ 
alter table EDUCATION_HISTORY MODIFY SCHOOL_TYPE varchar(20) ;

alter table EDUCATION_HISTORY MODIFY DATE_OF_JOINING date ;

alter table EDUCATION_HISTORY MODIFY DATE_OF_RELIVING date ;

alter table EDUCATION_HISTORY MODIFY ADDRESS_ID bigint(20) ;

alter table EDUCATION_HISTORY MODIFY SCHOOL_TYPE varchar(20) ;

alter table EDUCATION_HISTORY MODIFY MEDIAM varchar(20) ;

alter table EDUCATION_HISTORY MODIFY DATE_OF_JOINING date ;

alter table EDUCATION_HISTORY MODIFY DATE_OF_RELIVING date ;

alter table EDUCATION_HISTORY MODIFY ADDRESS_ID bigint(20) ;

alter table EDUCATION_HISTORY MODIFY HIGHEST_CLASS varchar(20) ;

alter table EDUCATION_HISTORY CHANGE MEDIAM MEDIUM varchar (20) ;


/**
 * End for Admission Process Changes
 */

alter table EDUCATION_HISTORY DROP COLUMN MEDIAM;
ALTER TABLE PICK_UP_POINT_FEE_CATALOG DROP COLUMN PAYMENT_DATE;


alter table STUDENT MODIFY RELIGION varchar(50) ;
 
alter table STUDENT MODIFY MOTHER_TONGUE varchar(50);
 
alter table STUDENT MODIFY RESERVATION varchar(50);

alter table STUDENT DROP COLUMN studentAttendanceForMonth;

update BUILDING_BLOCK set NEW_ADMISS_FEE=0;

update BUILDING_BLOCK set FEE_TYPE = 'APPLICATION_FEE' WHERE FEE_TYPE = 'APPLICATION_FORM_FEE';


---19/07/2013
alter table STUDENT MODIFY APPLIED_BATCH_ID bigint(20) ;
alter table STUDENT_ACADEMIC_YEAR MODIFY BATCH_ID bigint(20) ;
update BRANCH_RULE set BATCH_REQUIRED_IND=1;

alter table BRANCH_BANK_ACCOUNT DROP COLUMN CURRENT_BALANCE;

----03/08/2013
ALTER TABLE BRANCH_BALANCE_SHEET DROP COLUMN PROCESSED;
ALTER TABLE BRANCH_BALANCE_SHEET CHANGE COLUMN CLOSING_BALANCE CLOSING_BALANCE DOUBLE NULL  ;
ALTER TABLE BRANCH_BALANCE_SHEET CHANGE COLUMN END_DATE END_DATE DATE NULL  ;


update STUDENT set STUDENT_STATUS = 'ACCEPT_FOR_DROPOUT' where  STUDENT_STATUS = 'IN_DROPOUT';

ALTER TABLE PICK_UP_POINT_FEE_CATALOG` DROP COLUMN PAYMENT_DATE;


---09/03/2013
ALTER TABLE EMPLOYEE_DESIGNATION DROP COLUMN COMMENTS;

---01/03/2014
update BATCH_LOG set BATCH_NOTIFICATION_SENT_FOR = 'STUDENTS' where id>0;
update BATCH_LOG set BATCH_NOTIFICATION_SENT_FOR = 'ADMISSIONS' where BATCH_NOTIFICATION_LEVEL='STUDENT' and id>0;

