/**
 * Alter columns
 */
ALTER TABLE STUDENT_FEE_TXN CHANGE COLUMN PAYMENT_METHOD PAYMENT_METHOD VARCHAR(255) NULL;






/**drop procedure if exists schema_change;  
  
delimiter ';;'  
create procedure schema_change() begin  
  
 /* delete columns if they exist */  
 if exists (select * from information_schema.columns where table_name = 'USER_ACCOUNT' and column_name = 'PASSWORD_CHANGED_DATE') then  
  alter table USER_ACCOUNT drop column PASSWORD_CHANGED_DATE;  
 end if;  
 
  if exists (select * from information_schema.columns where table_name = 'USER_ACCOUNT' and column_name = 'LOGIN_USER_ID') then  
  alter table USER_ACCOUNT drop column LOGIN_USER_ID;  
 end if; 
 
 
  if exists (select * from information_schema.columns where table_name = 'USER_ACCOUNT' and column_name = 'LOGIN_TYPE') then  
  alter table USER_ACCOUNT drop column LOGIN_TYPE;  
 end if; 
    
end;;  
  
delimiter ';'  

call schema_change();  
  
drop procedure if exists schema_change; **/


ALTER TABLE USER_ACCOUNT DROP COLUMN PASSWORD_CHANGED_DATE , DROP COLUMN LOGIN_USER_ID , DROP COLUMN LOGIN_TYPE ;

ALTER TABLE BATCH DROP COLUMN START_DATE , DROP COLUMN END_DATE ;

update STUDENT set APPLIED_BATCH_ID = 1;

UPDATE STUDENT SET APPLIED_ACADEMIC_YEAR_ID = ACADEMIC_YEAR_ID;

UPDATE STUDENT SET APPLIED_CLASS_ID = APPLIED_FOR_CLASS_ID;

ALTER TABLE STUDENT DROP FOREIGN KEY FKBACA0E1BEE03080F , DROP FOREIGN KEY FKBACA0E1BD6191354 ;

ALTER TABLE STUDENT DROP COLUMN APPLIED_FOR_CLASS_ID , DROP COLUMN ACADEMIC_YEAR_ID , DROP INDEX FKBACA0E1BD6191354 , DROP INDEX FKBACA0E1BEE03080F ;


/**
 * SRI MEDHA DATA BASE
 */

UPDATE BUILDING_BLOCK SET FEE_TYPE= 'TUITION_FEE' WHERE  FEE_TYPE= 'LIBRARY_FEE' or FEE_TYPE= 'ADMISSION_FEE';

DELETE FROM BRANCH_ASSEMBLY WHERE BUILDING_BLOCK_ID IN (select ID from BUILDING_BLOCK where type = 'EMPLOYEE_CATEGORY');

ALTER TABLE EMPLOYEE_DESIGNATION DROP FOREIGN KEY FKD3D313C6DB19364A ;

ALTER TABLE EMPLOYEE_DESIGNATION DROP COLUMN EMPLOYMENT_TYPE_BUILD_BLK_ID , DROP INDEX FKD3D313C6DB19364A ;

delete FROM BUILDING_BLOCK where type = 'EMPLOYEE_CATEGORY';

UPDATE SECTION SET OPEN_FOR_ADMISSION_IND = 1;

UPDATE EMPLOYEE_DESIGNATION SET EMPLOYMENT_TYPE = 'PERMANENT'; 

ALTER TABLE CLASS_FEE RENAME TO CLASS_LEVEL_FEE;

ALTER TABLE CLASS_FEE_PAYMENT RENAME TO  CLASS_LEVEL_FEE_CATALOG;

UPDATE CLASS_LEVEL_FEE_CATALOG SET CLASS_LEVEL_FEE_ID = CLASS_FEE_ID;

UPDATE STUDENT_FEE_TXN_DETAILS SET KLASS_LEVEL_FEE_CATALOG_ID = KLASS_FEE_PAYMENT;

ALTER TABLE STUDENT_FEE_TXN_DETAILS DROP COLUMN KLASS_FEE_PAYMENT, DROP INDEX FK1454D3B05FDA3323;

ALTER TABLE  CLASS_LEVEL_FEE_CATALOG DROP FOREIGN KEY FK5C0679A69FA4ECCC;

ALTER TABLE  CLASS_LEVEL_FEE_CATALOG DROP COLUMN CLASS_FEE_ID, DROP INDEX `FK5C0679A69FA4ECCC` ;

UPDATE STUDENT_SECTION SET ACTION_DATE = AUDIT_TIMESTAMP;

UPDATE STUDENT_ACADEMIC_YEAR SET SEQUENCE_NR = 1;

UPDATE ACADEMIC_YEAR SET  CLASS_START_DATE = START_DATE;
