/**
Users
apeironsol
**/
insert into USER_ACCOUNT (ID, VERSION, ACC_EXPIRED, ACC_LOCKED, ACTIVE, CRDTLS_EXPIRED, PASSWORD, USERNAME, AUDIT_TIMESTAMP, AUDIT_USER_NAME) values(1, 1, 0, 0, 1, 0, '/x/2nTS83P0nTK8Eio/mXB701NbgYbvw', 'apeironsol',now(),'apeironsol');
insert into USER_ROLE (ID, VERSION, AUDIT_TIMESTAMP, AUDIT_USER_NAME,USER_ROLE,USER_ACCOUNT_ID) values(1, 0, now(), 'apeironsol', 'ROLE_APEIRONSOL',1);

insert into USER_ACCOUNT (ID, VERSION, ACC_EXPIRED, ACC_LOCKED, ACTIVE, CRDTLS_EXPIRED, PASSWORD, USERNAME, AUDIT_TIMESTAMP, AUDIT_USER_NAME) values(2, 1, 0, 0, 1, 0, '/x/2nTS83P0nTK8Eio/mXB701NbgYbvw', 'admin',now(),'apeironsol');
insert into USER_ROLE (ID, VERSION, AUDIT_TIMESTAMP, AUDIT_USER_NAME,USER_ROLE,USER_ACCOUNT_ID) values(2, 0, now(), 'apeironsol', 'ROLE_ADMIN',2);



/**Countries**/
INSERT INTO COUNTRY (ISO2_CODE,NAME,ISO3_CODE,NUM_CODE) VALUES ('IN','India','IND','356');

commit;