DELIMITER $$
DROP PROCEDURE IF EXISTS addressMobileNrFormat $$

CREATE PROCEDURE addressMobileNrFormat()
BEGIN
  
  DECLARE iterator  INT          DEFAULT 1;
  DECLARE output    VARCHAR(255) DEFAULT '';
  DECLARE VFIRST   VARCHAR(3);
  DECLARE VMIDDLE   VARCHAR(3);
  DECLARE VLAST     VARCHAR(10);
  DECLARE OUTP      TEXT DEFAULT 'TEST';
  DECLARE VID INT;
  DECLARE VMOBILE_NR VARCHAR(20);
  DECLARE CUR1 CURSOR FOR SELECT ID,MOBILE_NR FROM ADDRESS;

  IF EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ADDRESS' AND COLUMN_NAME = 'MOBILE_NR2') THEN 
	ALTER TABLE ADDRESS DROP COLUMN MOBILE_NR2;
  END IF;

  ALTER TABLE ADDRESS ADD COLUMN MOBILE_NR2 VARCHAR(20);

  UPDATE ADDRESS SET MOBILE_NR2 = NULL;

  OPEN CUR1;

	BEGIN 
	
	DECLARE EXIT HANDLER FOR NOT FOUND BEGIN END;

	LOOP 

	FETCH CUR1 INTO VID,VMOBILE_NR;

	WHILE iterator < (LENGTH(VMOBILE_NR) + 1) DO

      IF SUBSTRING(VMOBILE_NR, iterator, 1) IN ( '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ) THEN

         SET output = CONCAT(output, SUBSTRING(VMOBILE_NR, iterator, 1));

      END IF;

      SET iterator = iterator + 1;

	END WHILE;

	select SUBSTRING(VMOBILE_NR,1,3) FIRST , SUBSTRING(VMOBILE_NR,4,3) MIDDLE, SUBSTRING(VMOBILE_NR,7,(LENGTH(VMOBILE_NR)-6));

	SET output = CONCAT('+91-',SUBSTRING(VMOBILE_NR,1,3),'-', SUBSTRING(VMOBILE_NR,4,3),'-', SUBSTRING(VMOBILE_NR,7,(LENGTH(VMOBILE_NR)-6)));

	UPDATE ADDRESS SET MOBILE_NR2 = output WHERE ID = VID;

	END LOOP;

	END;

  CLOSE CUR1;

END;